dictionary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("mainapp.urls")),
    path('admin/', admin.site.urls),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    
]

mainapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("contact/", views.contact, name="contact"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register', kwargs={'redirect_authenticated_user': True}),
    path('accounts/profile/', views.profile, name='profile'),
]

mainapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add additional fields for the user profile
    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True)
    # ... other fields ...

    def __str__(self):
        return self.user.username

mainapp/forms.py
from django import forms
from .models import UserProfile
 
class IDict(forms.Form):
    sentence = forms.CharField()
    word = forms.CharField()
    response_language = forms.CharField()
    CHOICES = (('1', 1),('2', 2),('3', 3),('4', 4),('5', 5),)
    number_of_meanings = forms.ChoiceField(choices=CHOICES)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'avatar']

mainapp/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import IDict
from .forms import UserProfileForm, UserProfile
import openai
import json

openai.api_key = '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'


def get_completion(prompt, model="gpt-3.5-turbo",temperature=0):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temperature, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]
def get_response(sentence, word, number_of_meanings=3, response_language="English"):
    prompt = f"""
        You are an intelligent dictionary.
        Given a sentence and a word in that sentence, you need to:

        1. Identify the language of the sentence.
        2. Provide up to {number_of_meanings} closest meanings in {response_language} to the meaning of the word in the sentence, along with their similarity scores.
        Include sample sentences in the identified language and their corresponding meanings in {response_language}.
        Ensure that the returned meanings are in {response_language}, and limit the sample sentences to a maximum of 20 words.

        3. Sort the meanings in descending order based on the similarity score.
        4. Format your response in JSON as follows:

        {{
            "Language": "",
            "Meanings": [
                {{
                    "meaning": "",
                    "similarity_score": "",
                    "example_sentence": "",
                    "example_sentence_meaning": ""
                }},
                ...
            ]
        }}
        
        The sentence is enclosed within triple backticks, and the word is enclosed within triple backticks.
        Sentence: ```{sentence}```
        Word: ```{word}```
    """

    response = get_completion(prompt, temperature=0.5)
    # print(response)
    return json.loads(response)

def search(request):
    if request.method == 'POST':
        form = IDict(request.POST)
        # print(form)
        if form.is_valid():
            # Process the form data
            # Access the form fields using form.cleaned_data dictionary
            sentence = form.cleaned_data['sentence']
            word = form.cleaned_data['word']
            response_language = form.cleaned_data['response_language']
            number_of_meanings = form.cleaned_data['number_of_meanings']
            
            # print(word, sentence, number_of_meanings, response_language)
            
            response = get_response(sentence, word, number_of_meanings, response_language)
            print(response, type(response))
            # Redirect to a success page or do further processing
            return render(request, 'search.html', {'form': form, 'response': response})
        else:
            print(form.errors.as_data())
    else:
        form = IDict()
    return render(request, 'search.html', {'form': form})

def index(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print (form)
        if form.is_valid():
            user = form.save()
            # Create UserProfile for the newly registered user
            UserProfile.objects.create(user=user)
            # Log the user in
            login(request, user)
            return redirect('login')  # Redirect to the homepage or any other desired page
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = UserProfileForm(instance=request.user.userprofile)
    return render(request, 'profile.html', {'form': form})

# @login_required
# def custom_login(request, *args, **kwargs):
#     # If user is already authenticated, redirect to their profile
#     print(1231231)
#     if request.user.is_authenticated:
#         return redirect('profile')

#     # If user is not authenticated, continue with the regular login view
#     return auth_login(request, *args, **kwargs)

mainapp/templates/contact.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
  <div class="container  mt-4">
      <h1>Get in touch</h1>
      <p>私につながろう！</p>
        <ul>
            <li><i class="fa-solid fa-envelope"></i> Email: a21dc530@dhw.ac.jp</li>
            <li><i class="fa-brands fa-instagram"></i> Instargram: @nmt_hihi</li>
        </ul>
    </div>  
{% endblock content %}

mainapp/templates/home.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
  <header>
    <div class="header_big  mt-4">
      <img src="{% static 'img/logo.png' %}" class="mb-2" alt="Logo" style="border-radius: 50%;">
      <h1>賢明な辞書</h1>
      <p class="span_header">ワードサーチをより速く、効率的に行うための革命的なウェブアプリケーションへようこそ！ 複数の定義をひとつひとつ探す従来の方法に別れを告げましょう。キーワードを入力し、文脈の文を提供するだけで、残りは私にお任せください。先進のアルゴリズムにより、文脈を分析し、キーワードに最も近い意味を提供します。貴重な時間と労力を節約します。単語の探求の未来を受け入れ、賢明なワードサーチツールの便利さを体験してください。指先での素早く正確な単語の意味に、こんにちはを言ってください！</p>
      
      <button><a href="{% url 'search' %}">はじめましょう！</a></button>
    </div>
  </header>  
{% endblock content %}   

mainapp/templates/profile.html
{% extends 'template.html' %}

{% block content %}
<div class="container mt-4">
  <h2>プロファイル</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存</button>
  </form>
</div>
{% endblock %}

mainapp/templates/search.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
      <div class="container mt-4">
        
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_word"><i class="fa-solid fa-underline"></i></label>
            <input type="text" name="word" class="form-control" required id="id_word" placeholder="文中のキーワード">
          </div>
          <div class="form-group">
            <label for="id_sentence"><i class="fa-regular fa-pen-to-square"></i></label>
            <input type="text" name="sentence" class="form-control" required id="id_sentence" placeholder="文脈の文">
          </div>

            <div class="form-group">
                <label for="id_response_language"><i class="fa-solid fa-language"></i></label>
                <!-- <input type="text" name="response_language" class="form-control" required id="id_response_language" placeholder="応答言語"> -->
                <select type="text" name="response_language" class="form-control" required id="id_response_language">
                  <option selected disabled>応答言語</option>
                  <option value="AB">Abkhazian</option>
                  <option value="AA">Afar</option>
                  <option value="AF">Afrikanns</option>
                  <option value="SQ">Albanian</option>
                  <option value="AM">Amharic</option>
                  <option value="AR">Arabic</option>
                  <option value="HY">Armenian</option>
                  <option value="AS">Assamese</option>
                  <option value="AY">Aymara</option>
                  <option value="AZ">Azerbaijani</option>
                  <option value="BA">Bashkir</option>
                  <option value="EU">Basque</option>
                  <option value="BN">Bengali, Bangla</option>
                  <option value="DZ">Bhutani</option>
                  <option value="BH">Bihari</option>
                  <option value="BI">Bislama</option>
                  <option value="BR">Breton</option>
                  <option value="BG">Bulgarian</option>
                  <option value="MY">Burmese</option>
                  <option value="BE">Byelorussian</option>
                  <option value="KM">Cambodian</option>
                  <option value="CA">Catalan</option>
                  <option value="ZH">Chinese (Mandarin)</option>
                  <option value="CO">Corsican</option>
                  <option value="HR">Croation</option>
                  <option value="CS">Czech</option>
                  <option value="DA">Danish</option>
                  <option value="NL">Dutch</option>
                  <option value="EN">English, American</option>
                  <option value="EO">Esperanto</option>
                  <option value="ET">Estonian</option>
                  <option value="FO">Faeroese</option>
                  <option value="FJ">Fiji</option>
                  <option value="FI">Finnish</option>
                  <option value="FR">French</option>
                  <option value="FY">Frisian</option>
                  <option value="GD">Gaelic (Scots Gaelic)</option>
                  <option value="GL">Galician</option>
                  <option value="KA">Georgian</option>
                  <option value="DE">German</option>
                  <option value="EL">Greek</option>
                  <option value="KL">Greenlandic</option>
                  <option value="GN">Guarani</option>
                  <option value="GU">Gujarati</option>
                  <option value="HA">Hausa</option>
                  <option value="IW">Hebrew</option>
                  <option value="HI">Hindi</option>
                  <option value="HU">Hungarian</option>
                  <option value="IS">Icelandic</option>
                  <option value="IN">Indonesian</option>
                  <option value="IA">Interlingua</option>
                  <option value="IE">Interlingue</option>
                  <option value="IK">Inupiak</option> 
                  <option value="GA">Irish</option>
                  <option value="IT">Italian</option>
                  <option value="JA">Japanese</option>
                  <option value="JW">Javanese</option>
                  <option value="KN">Kannada</option>
                  <option value="KS">Kashmiri</option>
                  <option value="KK">Kazakh</option>
                  <option value="RW">Kinyarwanda</option>
                  <option value="KY">Kirghiz</option>
                  <option value="RN">Kirundi</option>
                  <option value="KO">Korean</option>
                  <option value="KU">Kurdish</option>
                  <option value="LO">Laothian</option>
                  <option value="LA">Latin</option>
                  <option value="LV">Latvian, Lettish</option>
                  <option value="LN">Lingala</option>
                  <option value="LT">Lithuanian</option>
                  <option value="MK">Macedonian</option>
                  <option value="MG">Malagasy</option>
                  <option value="MS">Malay</option>
                  <option value="ML">Malayalam</option>
                  <option value="MT">Maltese</option>
                  <option value="MI">Maori</option>
                  <option value="MR">Marathi</option>
                  <option value="MO">Moldavian</option>
                  <option value="MN">Mongolian</option>
                  <option value="NA">Nauru</option>
                  <option value="NE">Nepali</option>
                  <option value="NO">Norwegian</option>
                  <option value="OC">Occitan</option>
                  <option value="OR">Oriya</option>
                  <option value="OM">Oromo, Afan</option>
                  <option value="PS">Pashto, Pushto</option>
                  <option value="FA">Persian</option>
                  <option value="PL">Polish</option>
                  <option value="PT">Portuguese</option>
                  <option value="PA">Punjabi</option>
                  <option value="QU">Quechua</option>
                  <option value="RM">Rhaeto-Romance</option>
                  <option value="RO">Romanian</option>
                  <option value="RU">Russian</option>
                  <option value="SM">Samoan</option>
                  <option value="SG">Sangro</option>
                  <option value="SA">Sanskrit</option>
                  <option value="SR">Serbian</option>
                  <option value="SH">Serbo-Croatian</option>
                  <option value="ST">Sesotho</option>
                  <option value="TN">Setswana</option>
                  <option value="SN">Shona</option>
                  <option value="SD">Sindhi</option>
                  <option value="SI">Singhalese</option>
                  <option value="SS">Siswati</option>
                  <option value="SK">Slovak</option>
                  <option value="SL">Slovenian</option>
                  <option value="SO">Somali</option>
                  <option value="ES">Spanish</option>
                  <option value="SU">Sudanese</option>
                  <option value="SW">Swahili</option>
                  <option value="SV">Swedish</option>
                  <option value="TL">Tagalog</option>
                  <option value="TG">Tajik</option>
                  <option value="TA">Tamil</option>
                  <option value="TT">Tatar</option>
                  <option value="TE">Telugu</option>
                  <option value="TH">Thai</option>
                  <option value="BO">Tibetan</option>
                  <option value="TI">Tigrinya</option>
                  <option value="TO">Tonga</option>
                  <option value="TS">Tsonga</option>
                  <option value="TR">Turkish</option>
                  <option value="TK">Turkmen</option>
                  <option value="TW">Twi</option>
                  <option value="UK">Ukranian</option>
                  <option value="UR">Urdu</option>
                  <option value="UZ">Uzbek</option>
                  <option value="VI">Vietnamese</option>
                  <option value="VO">Volapuk</option>
                  <option value="CY">Welsh</option>
                  <option value="WO">Wolof</option>
                  <option value="XH">Xhosa</option>
                  <option value="JI">Yiddish</option>
                  <option value="YO">Yoruba</option>
                  <option value="ZU">Zulu</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_number_of_meanings"><i class="fa-solid fa-list-ul"></i></label>
                <select class="form-control" name="number_of_meanings" id="id_number_of_meanings">
                    <option selected disabled>意味の数</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
          

          <button type="submit" class="btn btn-primary"><i class="fa-solid fa-magnifying-glass"></i>検索</button>
        </form>
      
      
        {% if response %}
        <div class="response">
          <h1>検出された言語： {{response.Language}}</h1>
          <table>
            <tr>
              <th>意味</th>
              <th>類似度スコア</th>
              <th>例文</th>
              <th>例文の意味</th>
            </tr>
            {% for m in response.Meanings %}
              <tr>
                <td>{{m.meaning}}</td> 
                <td>{{m.similarity_score}}</td> 
                <td>{{m.example_sentence}}</td>
                <td>{{m.example_sentence_meaning}}</td>
              </tr>
            {% endfor %}
          </table>
        </div>
        {% endif %}
      </div>
      {% endblock content %}

mainapp/templates/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@500&display=swap" rel="stylesheet">
  </head>
  <body>
  <main>
    <div id="container">
      <nav>
        <ul>
          <li><a href="{% url 'index' %}" title="ホーム"><i class="fa-solid fa-house" style="color: #ffffff;"></i></a></li>
          <li><a href="{% url 'search' %}" title="検索"><i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i></li>
          <li><a href="{% url 'contact' %}"title="私について"><i class="fa-solid fa-envelope-open-text" style="color: #ffffff;"></i></li>
        </ul>
        <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'profile' %}" title="プロファイル"><i class="fa-solid fa-user" style="color: #ffffff;"></i></a></li>
          <li><a href="{% url 'logout' %}" title="ログアウト"><i class="fa-solid fa-right-from-bracket" style="color: #ffffff;"></i></a></li>
        {% else %}
          <li>
            <a  href="{% url 'login' %}" title="ログイン"><i class="fa-solid fa-right-to-bracket fa-flip-horizontal" style="color: #ffffff;"></i></a>
          </li>
        {% endif %}
        </ul>
        
      </nav>
      {% block content %}
      {% endblock content %}
    </div>
  </main>

  <footer></footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/59a8359b77.js" crossorigin="anonymous"></script>
  </body>
</html>